# Generated by Django 2.1.7 on 2019-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190401_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_context',
            field=models.CharField(max_length=200, verbose_name='新闻内容'),
        ),
    ]
