# Generated by Django 2.1.7 on 2019-04-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190401_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
