# Generated by Django 2.1.7 on 2019-04-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
