# Generated by Django 2.1.7 on 2019-04-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
