# Generated by Django 2.1.7 on 2019-04-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_name', models.CharField(max_length=50, verbose_name='农产品名称')),
                ('ap_number', models.FloatField(max_length=20, verbose_name='农产品数量')),
                ('ap_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('ap_unit', models.CharField(default='500g', max_length=20, verbose_name='商品单位')),
                ('ap_area', models.CharField(max_length=20, verbose_name='农产品产地')),
                ('ap_mark', models.CharField(max_length=20, verbose_name='农产品备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('ap_click', models.IntegerField(verbose_name='点击量')),
            ],
            options={
                'verbose_name': '农产品信息',
                'verbose_name_plural': '农产品信息',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='类型名称')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ap_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.TypeInfo', verbose_name='所属分类'),
        ),
    ]
