# Generated by Django 2.1.7 on 2019-05-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ap_pic',
            field=models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='农产品图片'),
        ),
    ]
