# Generated by Django 2.1.7 on 2019-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_book_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户订单'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户权限'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_mark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户备注'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户账号'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户密码'),
        ),
    ]
