# Generated by Django 2.1.7 on 2019-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190407_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_password',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_farmer',
            field=models.BooleanField(null=True, verbose_name='是否为农民'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_book_id',
            field=models.CharField(max_length=20, verbose_name='用户订单'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_level',
            field=models.CharField(max_length=20, verbose_name='用户权限'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_mark',
            field=models.CharField(max_length=20, verbose_name='用户备注'),
        ),
    ]
