# Generated by Django 2.1.7 on 2019-04-19 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190408_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False, verbose_name='新闻序号')),
                ('news_title', models.CharField(max_length=20, verbose_name='新闻标题')),
                ('news_context', models.CharField(max_length=200, verbose_name='新闻内容')),
                ('news_mark', models.CharField(max_length=20, verbose_name='新闻备注')),
                ('news_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='新闻发布人')),
            ],
            options={
                'verbose_name': '新闻信息',
                'verbose_name_plural': '新闻信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单序号')),
                ('order_number', models.CharField(max_length=20, verbose_name='订单数量')),
                ('order_price', models.FloatField(max_length=20, verbose_name='订单总价')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订单用户')),
            ],
        ),
    ]
