# Generated by Django 2.1.7 on 2019-04-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_news_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_send',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
