# Generated by Django 2.1.7 on 2019-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190419_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_farmer',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_ardess',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_pc',
            field=models.CharField(default='', max_length=6),
        ),
    ]
