# Generated by Django 2.1.7 on 2019-04-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190423_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_ardess',
            new_name='user_adress',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_pc',
            field=models.CharField(default='', max_length=6, verbose_name='邮编'),
        ),
    ]
