# Generated by Django 2.1.7 on 2019-04-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190426_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_adress',
            new_name='user_address',
        ),
    ]
